# Lab Task 01

Write a function to return True if the first and last number of a given list is same. If numbers are different then return False.

In [2]:
# Given:
numbers_x = [10, 20, 30, 40, 10]
numbers_y = [75, 65, 35, 75, 30]


def check(lst):
    if lst[0]==lst[len(lst)-1]:
        return True
    else:
        return False

if check(numbers_x)==True:
    print ('result is True')
else:
    print ('result is False')
# Expected Output:
# Given list: [10, 20, 30, 40, 10]
# result is True

# numbers_y = [75, 65, 35, 75, 30]
# result is False

result is True






# Lab Task 02

Create two NumPy arrays of the same shape and perform element-wise addition on them.

Calculate the element-wise product of two NumPy arrays.

In [13]:
#code here
import numpy as np
arr= np.arange(0,12)
arr2=np.arange(12,24)
sum=np.add(arr,arr2)
print (sum)
product=np.multiply(arr,arr2)
print(product)

[12 14 16 18 20 22 24 26 28 30 32 34]
[  0  13  28  45  64  85 108 133 160 189 220 253]


# Lab Task 03

Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

Concatenate two NumPy arrays horizontally and vertically.

In [26]:
#code here
arr=np.arange(0,12)
arr=arr.reshape(3,4)

arr2=np.array([[0,1,2],[4,5,6]])
arr3=np.array([[7,8,9],[10,11,12]])
print(np.concatenate((arr2,arr3),axis=1))
print (np.concatenate((arr2,arr3),axis=0))

[[ 0  1  2  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 0  1  2]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Lab Task 04




## Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.


In [28]:
products = {
    1: 'Laptop',
    2: 'keyboard',
    3: 'Mouse'
}
shopping_cart = {}

print('Welcome to our Store!!')
print('Available products:')
for key, value in products.items():
    print(f'{key}: {value}')

while True:
    choice = input("Enter the number corresponding to the product (press 'q' to quit): ")

    if choice.lower() == 'q':
        break

    try:
        choice = int(choice)
        if choice not in products:
            print('Please enter a valid product number.')
            continue
        product_name = products[choice]
        
        if product_name in shopping_cart:
            shopping_cart[product_name] += 1
        else:
            shopping_cart[product_name] = 1

        print(f'{product_name} added to the cart.')

    except ValueError:
        print('Please enter a valid product number.')

print('\nYour Shopping Cart:')
for product, quantity in shopping_cart.items():
    print(f'- {quantity} {product}(s)')

print('Thank you for shopping with us. Goodbye!')

Welcome to the Online Store!
Available products:
1: Laptop
2: Headphones
3: Mouse


Headphones added to the cart.

Your Shopping Cart:
- 1 Headphones(s)
Thank you for shopping with us. Goodbye!


# Lab Task 05


## Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [29]:
#code here
def classify_emails(emails):
    imp_keywords = ['urgent', 'important', 'action required']
    promo_keywords = ['sale', 'discount', 'promotion', 'offer']
    spam_keywords = ['lottery', 'you have won']

    important_emails = []
    promotions_emails = []
    spam_emails = []

    for email in emails:
        email_lower = email.lower()
        if any(keyword in email_lower for keyword in imp_keywords):
            important_emails.append(email)
        elif any(keyword in email_lower for keyword in promo_keywords):
            promotions_emails.append(email)
        elif any(keyword in email_lower for keyword in spam_keywords):
            spam_emails.append(email)

    return important_emails, promotions_emails, spam_emails

emails = [
    "URGENT: have you submitted the assigned task or no?",
    "check out our latest sale",
    'congratulations! you have won a lottery',
    'important message: please read'
]


important, promotions, spam = classify_emails(emails)


print("Important Emails:")
for email in important:
    print("-", email)

print("\nPromotions Emails:")
for email in promotions:
    print("-", email)

print("\nSpam Emails:")
for email in spam:
    print("-", email)



Important Emails:
- URGENT: have you submitted the assigned task or no?
- important message: please read

Promotions Emails:
- check out our latest sale

Spam Emails:
- congratulations! you have won a lottery


# Lab Task 06

## English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [42]:
#code here

english_to_spanish = {
    "hello": "hola",
    "goodbye": "adiós",
    "cat": "gato",
    "dog": "perro",
    "book": "libro",
    "dondestalabebioteka":"where is the library",
    "chupa mi culo":"hello how are you"
}


def translate_word(word):
    if word in english_to_spanish:
        return english_to_spanish[word]
    else:
        return None


while True:
   
    user_input = input("Enter an English word (or type 'exit' to quit): ").lower()

    
    if user_input == 'exit':
        print("Exiting...")
        break


    translation = translate_word(user_input)

 
    if translation:
        print(f"The Spanish translation of '{user_input}' is '{translation}'.")
    else:
        print(f"Sorry, the translation of '{user_input}' is not available.")


The Spanish translation of 'hello' is 'hola'.
Sorry, the translation of '' is not available.
Sorry, the translation of '' is not available.
Sorry, the translation of '' is not available.
Sorry, the translation of '' is not available.
Sorry, the translation of '' is not available.
Sorry, the translation of '' is not available.
Sorry, the translation of '' is not available.
Sorry, the translation of '' is not available.
Sorry, the translation of '' is not available.
Sorry, the translation of '' is not available.
Sorry, the translation of '' is not available.
Sorry, the translation of '' is not available.


# Lab Task 07

dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [38]:
import pandas as pd
df=pd.read_csv('https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv')
df


Rank                                              Name Platform  \
0          1                                        Wii Sports      Wii   
1          2                                 Super Mario Bros.      NES   
2          3                                    Mario Kart Wii      Wii   
3          4                                 Wii Sports Resort      Wii   
4          5                          Pokemon Red/Pokemon Blue       GB   
...      ...                                               ...      ...   
16593  16596                Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                     Men in Black II: Alien Escape       GC   
16595  16598  SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                        Know How 2       DS   
16597  16600                                  Spirits & Spells      GBA   

         Year         Genre   Publisher  NA_Sales  EU_Sales  JP_Sales  \
0      2006.0        Sports    Nintendo     41.49     29.02      3.77   
1      1985.0      Platform    Nintendo     29.08      3.58      6.81   
2      2008.0        Racing    Nintendo     15.85     12.88      3.79   
3      2009.0        Sports    Nintendo     15.75     11.01      3.28   
4      1996.0  Role-Playing    Nintendo     11.27      8.89     10.22   
...       ...           ...         ...       ...       ...       ...   
16593  2002.0      Platform       Kemco      0.01      0.00      0.00   
16594  2003.0       Shooter  Infogrames      0.01      0.00      0.00   
16595  2008.0        Racing  Activision      0.00      0.00      0.00   
16596  2010.0        Puzzle    7G//AMES      0.00      0.01      0.00   
16597  2003.0      Platform     Wanadoo      0.01      0.00      0.00   

       Other_Sales  Global_Sales  
0             8.46         82.74  
1             0.77         40.24  
2             3.31         35.82  
3             2.96         33.00  
4             1.00         31.37  
...            ...           ...  
16593         0.00          0.01  
16594         0.00          0.01  
16595         0.00          0.01  
16596         0.00          0.01  
16597         0.00          0.01  

[16598 rows x 11 columns]

In [41]:

total_global_sales=df['Global_Sales'].sum()
print("total global sales:",df['Global_Sales'].sum())
print ('highest global slaes:',df['Global_Sales'].max())

average_sales_per_region = df[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].mean()
print("\nAverage Sales for Each Region:")
print(average_sales_per_region)


top_5_genres_global_sales = df.groupby('Genre')['Global_Sales'].sum().nlargest(5)
print("\nTop 5 Most Popular Game Genres Based on Global Sales:")
print(top_5_genres_global_sales)


total_sales_per_genre_per_region = df.groupby('Genre')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()


most_popular_genre_na_sales = total_sales_per_genre_per_region['NA_Sales'].idxmax()
print("\nMost Popular Genre in North America (NA_Sales):", most_popular_genre_na_sales)


print("\nLast 10 Rows of the Dataset:")
print(df.tail(10))


top_3_platforms_global_sales = df.groupby('Platform')['Global_Sales'].sum().nlargest(3)
print("\nTop 3 Gaming Platforms with the Highest Global Sales:")
print(top_3_platforms_global_sales)


market_share_per_genre = (df.groupby('Genre')['Global_Sales'].sum() / total_global_sales) * 100
print("\nMarket Share (Percentage of Global Sales) for Each Genre:")
print(market_share_per_genre)

# Calculate the correlation coefficient between NA_Sales and EU_Sales
correlation_coefficient = df['NA_Sales'].corr(df['EU_Sales'])
print("\nCorrelation Coefficient between NA_Sales and EU_Sales:", correlation_coefficient)

total global sales: 8920.44
highest global slaes: 82.74

Average Sales for Each Region:
NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64

Top 5 Most Popular Game Genres Based on Global Sales:
Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64

Most Popular Genre in North America (NA_Sales): Action

Last 10 Rows of the Dataset:
        Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpeck